import { useState, useRef } from "react";
import { flushSync } from "react-dom";
import {
  Table,
  Tag,
  Input,
  Modal,
  Select,
  Button,
  Descriptions,
  Tooltip,
  Dropdown,
  DatePicker,
  Spin, Space,
} from "antd";
import {
  SearchOutlined,
  EyeOutlined,
  EditOutlined,
  DownloadOutlined,
  DownOutlined,
  CheckOutlined,
} from "@ant-design/icons";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { pdf } from "@react-pdf/renderer";
import { ReactQRCode } from "@lglab/react-qr-code";
import { Image as AntImage } from "antd";
import styles from "../../styles/AllTransactionsComp.module.css";
import { supabase } from "../../../../config/supabaseClient";
import {
  PAYMENT_STATUS,
  PAYMENT_STATUS_OPTIONS,
  PAYMENT_STATUS_COLOR,
  PAYMENT_STATUS_SUMMARY_STYLE,
  PAYMENT_STATUS_WATERMARK,
  NOTIFICATION_TYPE,
} from "../../../../config/statusAndRoleConfig";
import {
  QK_ALL_TRANSACTIONS,
  QK_FEE_TYPES,
  QK_NOTIFICATIONS,
  QK_SESSIONS,
  QK_TRANSACTION_SUMMARY,
} from "../../../../config/queryKeyConfig";
import { showToast } from "../../../../components/layout/CustomToast";
import { useAuth } from "../../../../context/AuthProvider";
import ReceiptPDFDocument from "./ReceiptPDFDocument";
import { getFormattedTime } from "../../../../utils/dateUtil";

const PAGE_SIZE_OPTIONS = [5, 10, 50, 100, 200,500];
const DEFAULT_PAGE_SIZE = 10;

const formatDate = (d) => {
  if (!d) return "—";
  return new Date(d).toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
};

const paymentStatusLabelMap = Object.fromEntries(
  PAYMENT_STATUS_OPTIONS.map(({ value, label }) => [value, label]),
);

const CSV_COLUMNS = [
  { header: "Receipt ID", key: "receipt_id" },
  {
    header: "Date Issued",
    getValue: (r) => formatDate(r.receipt_gen_date),
  },
  { header: "Student Name", key: "student_name" },
  { header: "Student Email", key: "student_email" },
  { header: "Student Phone", key: "student_phone" },
  { header: "Session", key: "session" },
  { header: "Fee Type", key: "fee_type_title" },
  { header: "Extra Info", key: "fee_type_xtra_info" },
  {
    header: "Amount (BDT)",
    getValue: (r) =>
      r.amount != null ? Number(r.amount).toLocaleString() : "",
  },
  { header: "Payment Mode", key: "payment_mode" },
  { header: "Transaction ID", key: "trxn_id" },
  {
    header: "Due Date",
    getValue: (r) => formatDate(r.due_date),
  },
  {
    header: "Payment Date",
    getValue: (r) => formatDate(r.payment_date),
  },
  {
    header: "Status",
    getValue: (r) =>
      paymentStatusLabelMap[r.payment_status] ?? r.payment_status ?? "",
  },
  { header: "Generated By", key: "receipt_gen_by_email" },
  { header: "Verified By", key: "receipt_verified_by_email" },
  { header: "Student Remarks", key: "remarks_by_student" },
  {
    header: "Submitted At",
    getValue: (r) =>
      r.payment_submission_time
        ? getFormattedTime(r.payment_submission_time, "DD MMM YYYY, h:mm A")
        : "",
  },
];

const escapeCsvCell = (value) => {
  if (value == null || value === "") return "";
  const str = String(value);
  if (/[",\n\r]/.test(str)) return `"${str.replace(/"/g, '""')}"`;
  return str;
};

const applyTransactionFilters = (
  query,
  {
    searchQuery,
    selectedMonth,
    selectedPaymentMonth,
    selectedPaymentStatus,
    selectedSession,
    selectedFeeType,
    feeTypesData,
  },
) => {
  if (searchQuery) {
    query = query.or(
      `student_email.ilike.%${searchQuery}%,student_phone.ilike.%${searchQuery}%,receipt_id.ilike.%${searchQuery}%`,
    );
  }

  if (selectedMonth) {
    const start = selectedMonth.startOf("month").format("YYYY-MM-DD");
    const end = selectedMonth.endOf("month").format("YYYY-MM-DD");
    query = query.gte("receipt_gen_date", start).lte("receipt_gen_date", end);
  }

  if (selectedPaymentMonth) {
    const start = selectedPaymentMonth.startOf("month").format("YYYY-MM-DD");
    const end = selectedPaymentMonth.endOf("month").format("YYYY-MM-DD");
    query = query.gte("created_at", start).lte("created_at", end);
  }

  if (selectedPaymentStatus) {
    query = query.eq("payment_status", selectedPaymentStatus);
  }

  if (selectedSession) {
    query = query.eq("session", selectedSession);
  }

  if (selectedFeeType) {
    if (selectedFeeType === "__other__") {
      const knownTitles = feeTypesData.map((ft) => ft.fee_type_title);
      if (knownTitles.length > 0) {
        query = query.not(
          "fee_type_title",
          "in",
          `(${knownTitles.map((t) => `"${t}"`).join(",")})`,
        );
      }
    } else {
      query = query.eq("fee_type_title", selectedFeeType);
    }
  }

  return query;
};

const enrichTransactionsWithStudentNames = async (payments) => {
  const rows = payments ?? [];
  const emails = [...new Set(rows.map((r) => r.student_email).filter(Boolean))];
  const nameMap = {};

  if (emails.length > 0) {
    const { data: students, error } = await supabase
      .from("student")
      .select("email, name")
      .in("email", emails);
    if (error) throw new Error(error.message);
    (students ?? []).forEach((s) => {
      nameMap[s.email] = s.name;
    });
  }

  return rows.map((r) => ({
    ...r,
    student_name: nameMap[r.student_email] ?? null,
  }));
};

const fetchFilteredTransactionsForExport = async (
  filters,
  { page, limit },
) => {
  const from = (page - 1) * limit;
  const to = from + limit - 1;

  let query = supabase
    .from("student_payment")
    .select("*")
    .order("receipt_gen_date", { ascending: false })
    .range(from, to);

  query = applyTransactionFilters(query, filters);

  const { data, error } = await query;
  if (error) throw new Error(error.message);

  return enrichTransactionsWithStudentNames(data);
};

const buildTransactionsCsv = (rows) => {
  const headerRow = CSV_COLUMNS.map((col) => escapeCsvCell(col.header)).join(
    ",",
  );
  const dataRows = rows.map((row) =>
    CSV_COLUMNS.map((col) => {
      const raw = col.getValue ? col.getValue(row) : row[col.key];
      return escapeCsvCell(raw ?? "");
    }).join(","),
  );
  return [headerRow, ...dataRows].join("\r\n");
};

const svgContainerToDataUrl = (container) =>
  new Promise((resolve) => {
    if (!container) return resolve(null);
    const svg = container.querySelector("svg");
    if (!svg) return resolve(null);
    const svgString = new XMLSerializer().serializeToString(svg);
    const svgDataUrl = `data:image/svg+xml;base64,${btoa(
      unescape(encodeURIComponent(svgString)),
    )}`;
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = 200;
      canvas.height = 200;
      const ctx = canvas.getContext("2d");
      ctx.fillStyle = "#ffffff";
      ctx.fillRect(0, 0, 200, 200);
      ctx.drawImage(img, 0, 0, 200, 200);
      resolve(canvas.toDataURL("image/png"));
    };
    img.onerror = () => resolve(svgDataUrl);
    img.src = svgDataUrl;
  });

const AllTransactionsComp = () => {
  const queryClient = useQueryClient();
  const { user } = useAuth();
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE);
  const [searchQuery, setSearchQuery] = useState("");

  const [viewRecord, setViewRecord] = useState(null);
  const [downloadingId, setDownloadingId] = useState(null);
  const [qrDownloadUrl, setQrDownloadUrl] = useState(null);
  const qrRef = useRef(null);

  const [statusRecord, setStatusRecord] = useState(null);
  const [selectedStatus, setSelectedStatus] = useState(null);
  const [selectedMonth, setSelectedMonth] = useState(null);
  const [selectedPaymentMonth, setSelectedPaymentMonth] = useState(null);
  const [selectedFeeType, setSelectedFeeType] = useState(null);
  const [selectedPaymentStatus, setSelectedPaymentStatus] = useState(null);
  const [selectedSession, setSelectedSession] = useState(null);
  const [exportingCsv, setExportingCsv] = useState(false);

  const { data: sessionsData = [] } = useQuery({
    queryKey: [QK_SESSIONS],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("session")
        .select("session_name")
        .eq("is_active", true)
        .order("order", { ascending: true, nullsFirst: false });
      if (error) throw error;
      return data;
    },
    staleTime: 1000 * 60 * 10,
  });

  const { data: feeTypesData = [] } = useQuery({
    queryKey: [QK_FEE_TYPES],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("fee_type")
        .select("fee_type_title")
        .order("view_order", { ascending: true });
      if (error) throw error;
      return data;
    },
    staleTime: 1000 * 60 * 10,
  });

  const feeTypeItems = [
    {
      key: "__all__",
      label: <span>All Fee Types</span>,
      onClick: () => {
        setSelectedFeeType(null);
        setCurrentPage(1);
      },
    },
    ...feeTypesData.map((ft) => ({
      key: ft.fee_type_title,
      label: <span>{ft.fee_type_title}</span>,
      onClick: () => {
        setSelectedFeeType(ft.fee_type_title);
        setCurrentPage(1);
      },
    })),
    {
      key: "__other__",
      label: <span>Other</span>,
      onClick: () => {
        setSelectedFeeType("__other__");
        setCurrentPage(1);
      },
    },
  ];

  const hasActiveFilter = !!(
    searchQuery ||
    selectedMonth ||
    selectedPaymentMonth ||
    selectedFeeType ||
    selectedPaymentStatus ||
    selectedSession
  );

  const statusFilterLabel = selectedPaymentStatus
    ? (paymentStatusLabelMap[selectedPaymentStatus] ?? selectedPaymentStatus)
    : "Paid";

  const statusCardStyle =
    PAYMENT_STATUS_SUMMARY_STYLE[
      selectedPaymentStatus ?? PAYMENT_STATUS.PAID
    ] ?? PAYMENT_STATUS_SUMMARY_STYLE[PAYMENT_STATUS.PAID];

  const activeFilterChips = [
    selectedFeeType === "__other__" ? "Other Fee Types" : selectedFeeType,
    selectedSession,
    selectedMonth ? `Issued: ${selectedMonth.format("MMM YYYY")}` : null,
    selectedPaymentMonth
      ? `Payment: ${selectedPaymentMonth.format("MMM YYYY")}`
      : null,
    searchQuery ? `"${searchQuery}"` : null,
    selectedPaymentStatus ? paymentStatusLabelMap[selectedPaymentStatus] : null,
  ].filter(Boolean);

  const { data: summaryData, isLoading: summaryLoading } = useQuery({
    queryKey: [
      QK_TRANSACTION_SUMMARY,
      searchQuery,
      selectedMonth?.format("YYYY-MM"),
      selectedPaymentMonth?.format("YYYY-MM"),
      selectedFeeType,
      selectedPaymentStatus,
      selectedSession,
    ],
    queryFn: async () => {
      const knownFeeTypes = feeTypesData.map((ft) => ft.fee_type_title);
      const { data: rpcData, error } = await supabase.rpc(
        "get_transaction_summary",
        {
          p_search_query: searchQuery || null,
          p_issued_month_start: selectedMonth
            ? selectedMonth.startOf("month").format("YYYY-MM-DD")
            : null,
          p_issued_month_end: selectedMonth
            ? selectedMonth.endOf("month").format("YYYY-MM-DD")
            : null,
          p_payment_month_start: selectedPaymentMonth
            ? selectedPaymentMonth.startOf("month").format("YYYY-MM-DD")
            : null,
          p_payment_month_end: selectedPaymentMonth
            ? selectedPaymentMonth.endOf("month").format("YYYY-MM-DD")
            : null,
          p_fee_type:
            selectedFeeType && selectedFeeType !== "__other__"
              ? selectedFeeType
              : null,
          p_fee_type_is_other: selectedFeeType === "__other__",
          p_payment_status: selectedPaymentStatus || null,
          p_session: selectedSession || null,
          p_known_fee_types:
            selectedFeeType === "__other__" && knownFeeTypes.length > 0
              ? knownFeeTypes
              : null,
        },
      );
      if (error) throw new Error(error.message);
      return rpcData?.[0] ?? { total_issued: 0, total_for_status: 0 };
    },
    enabled: hasActiveFilter,
  });

  const { data, isLoading, isFetching } = useQuery({
    queryKey: [
      QK_ALL_TRANSACTIONS,
      currentPage,
      pageSize,
      searchQuery,
      selectedMonth,
      selectedPaymentMonth,
      selectedFeeType,
      selectedPaymentStatus,
      selectedSession,
    ],
    queryFn: async () => {
      const from = (currentPage - 1) * pageSize;
      const to = from + pageSize - 1;

      let query = supabase
        .from("student_payment")
        .select("*", { count: "exact" })
        .order("receipt_gen_date", { ascending: false })
        .range(from, to);

      query = applyTransactionFilters(query, {
        searchQuery,
        selectedMonth,
        selectedPaymentMonth,
        selectedPaymentStatus,
        selectedSession,
        selectedFeeType,
        feeTypesData,
      });

      const { data: payments, error, count } = await query;
      if (error) throw new Error(error.message);

      const rows = await enrichTransactionsWithStudentNames(payments);

      return {
        rows,
        total: count ?? 0,
      };
    },
  });

  const { mutate: updateStatus, isPending: statusUpdating } = useMutation({
    mutationFn: async ({ receipt_id, payment_status, verified_by_email }) => {
      const { error } = await supabase
        .from("student_payment")
        .update({
          payment_status,
          receipt_verified_by_email: verified_by_email,
        })
        .eq("receipt_id", receipt_id);
      if (error) throw new Error(error.message);
    },
    onSuccess: async (_, variables) => {
      queryClient.invalidateQueries({ queryKey: [QK_ALL_TRANSACTIONS] });
      const { receipt_id, payment_status, student_email } = variables;
      const statusLabel =
        paymentStatusLabelMap[payment_status] ?? payment_status;
      try {
        await supabase.from("notifications").insert({
          recipient_email: student_email,
          title: "Payment Status Updated",
          message: `Your payment status for receipt ${receipt_id} has been updated to "${statusLabel}". Visit My Finances for details.`,
          type: NOTIFICATION_TYPE.PAYMENT,
          redirection_link: "/dashboard/my-finances",
          recipient_user_type: "student",
        });
        queryClient.invalidateQueries({
          queryKey: [QK_NOTIFICATIONS, student_email],
        });
      } catch (_err) {
        // silent — notification is non-critical
      }
      showToast("Payment status updated.", "success");
      setStatusRecord(null);
      setSelectedStatus(null);
    },
    onError: (err) => {
      showToast(err.message || "Failed to update status.", "error");
    },
  });

  const handleDownload = async (record) => {
    setDownloadingId(record.receipt_id);
    try {
      let logoBase64 = null;
      try {
        const res = await fetch("/assets/logo_cut_nobg.png");
        const blob = await res.blob();
        logoBase64 = await new Promise((resolve) => {
          const reader = new FileReader();
          reader.onloadend = () => resolve(reader.result);
          reader.readAsDataURL(blob);
        });
      } catch (_) {
        // logo optional
      }

      let qrCodeSrc = null;
      if (record.payment_status !== PAYMENT_STATUS.PENDING) {
        const qrUrl = `${window.location.origin}/payment/verify/${record.receipt_id}`;
        flushSync(() => setQrDownloadUrl(qrUrl));
        qrCodeSrc = await svgContainerToDataUrl(qrRef.current);
        setQrDownloadUrl(null);
      }

      const blob = await pdf(
        <ReceiptPDFDocument
          receiptId={record.receipt_id}
          issuedDate={formatDate(record.receipt_gen_date)}
          studentName={record.student_name || record.student_email}
          studentEmail={record.student_email}
          studentPhone={record.student_phone || ""}
          studentSession={record.session || ""}
          feeType={record.fee_type_title}
          otherText=""
          formattedDueDate={formatDate(record.due_date)}
          amount={record.amount}
          additionalInfo={record.fee_type_xtra_info || ""}
          paymentMode={record.payment_mode || ""}
          paymentDate={
            record.payment_date ? formatDate(record.payment_date) : ""
          }
          transactionId={record.trxn_id || ""}
          remarks={record.remarks_by_student || ""}
          logoBase64={logoBase64}
          watermarkText={
            PAYMENT_STATUS_WATERMARK[record.payment_status] ?? "UNPAID"
          }
          qrCodeSrc={qrCodeSrc}
        />,
      ).toBlob();

      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `receipt-${record.receipt_id}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("PDF download failed:", err);

      showToast("Failed to download receipt.", "error");
    } finally {
      setDownloadingId(null);
    }
  };

  const columns = [
    {
      title: "RECEIPT ID",
      dataIndex: "receipt_id",
      key: "receipt_id",
      render: (v) => <span className={styles.cell}>{v ?? "—"}</span>,
    },
    {
      title: "DATE ISSUED",
      dataIndex: "receipt_gen_date",
      key: "receipt_gen_date",
      // render: (v) => <span className={styles.cell}>{formatDate(v)}</span>,
      render: (v) => (
        <span className={styles.cell}>
          {v ? getFormattedTime(v, "DD MMM YYYY, h:mm A") : "—"}
        </span>
      ),
    },
    {
      title: "STUDENT",
      key: "student",
      render: (_, r) => (
        <div>
          <div className={styles.cellBold}>
            {r.student_name ?? r.student_email ?? "—"}
          </div>
          <div className={styles.cellSub}>{r.student_email}</div>
          {r.student_phone && (
            <div className={styles.cellSub}>{r.student_phone}</div>
          )}
        </div>
      ),
    },
    {
      title: "FEE TYPE",
      key: "fee_type",
      render: (_, r) => (
        <div>
          <div className={styles.cellLink}>{r.fee_type_title ?? "—"}</div>
          {r.fee_type_xtra_info && (
            <div className={styles.cellSub}>{r.fee_type_xtra_info}</div>
          )}
        </div>
      ),
    },
    {
      title: "SESSION",
      dataIndex: "session",
      key: "session",
      render: (v) => <span className={styles.cell}>{v ?? "—"}</span>,
    },
    {
      title: "AMOUNT (BDT)",
      dataIndex: "amount",
      key: "amount",
      render: (v) => (
        <span className={styles.cell}>
          {v != null ? `BDT ${Number(v).toLocaleString()}` : "—"}
        </span>
      ),
    },
    {
      title: "STATUS",
      dataIndex: "payment_status",
      key: "payment_status",
      render: (v) => (
        <Tag color={PAYMENT_STATUS_COLOR[v] ?? "default"}>
          {paymentStatusLabelMap[v] ?? v ?? "—"}
        </Tag>
      ),
    },
    {
      title: "ACTIONS",
      key: "actions",
      fixed: "right",
      render: (_, record) => (
        <div style={{ display: "flex", gap: 8 }}>
          <Tooltip title="View Details">
            <Button
              size="small"
              icon={<EyeOutlined />}
              onClick={() => setViewRecord(record)}
            />
          </Tooltip>
          <Tooltip title="Change Status">
            <Button
              size="small"
              icon={<i className="fi fi-rr-career-growth"></i>}
              onClick={() => {
                setStatusRecord(record);
                setSelectedStatus(record.payment_status);
              }}
            />
          </Tooltip>
        </div>
      ),
    },
  ];

  const rows = data?.rows ?? [];
  const total = data?.total ?? 0;

  const handlePageSizeChange = (size) => {
    setPageSize(size);
    setCurrentPage(1);
  };

  const rowsMenuItems = PAGE_SIZE_OPTIONS.map((size) => ({
    key: String(size),
    label: (
      <span className={styles.rowsMenuItem}>
        {size}
        {pageSize === size && (
          <CheckOutlined className={styles.rowsMenuCheck} />
        )}
      </span>
    ),
    onClick: () => handlePageSizeChange(size),
  }));

  const showingFrom = total === 0 ? 0 : (currentPage - 1) * pageSize + 1;
  const showingTo = total === 0 ? 0 : Math.min(currentPage * pageSize, total);

  const onIssuedMonthChange = (date) => {
    setSelectedMonth(date ?? null);
    setCurrentPage(1);
  };

  const onPaymentMonthChange = (date) => {
    setSelectedPaymentMonth(date ?? null);
    setCurrentPage(1);
  };

  const transactionFilters = {
    searchQuery,
    selectedMonth,
    selectedPaymentMonth,
    selectedPaymentStatus,
    selectedSession,
    selectedFeeType,
    feeTypesData,
  };

  const downloadCSV = async () => {
    setExportingCsv(true);
    try {
      const exportRows = await fetchFilteredTransactionsForExport(
        transactionFilters,
        { page: currentPage, limit: pageSize },
      );

      if (!exportRows.length) {
        showToast("No transactions to export.", "warning");
        return;
      }

      const csv = buildTransactionsCsv(exportRows);
      const blob = new Blob([`\uFEFF${csv}`], {
        type: "text/csv;charset=utf-8;",
      });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `transactions-${new Date().toISOString().slice(0, 10)}.csv`;
      link.click();
      URL.revokeObjectURL(url);

      showToast(
        `Exported ${exportRows.length.toLocaleString()} transaction(s).`,
        "success",
      );
    } catch (err) {
      console.error("CSV export failed:", err);
      showToast(err.message || "Failed to export CSV.", "error");
    } finally {
      setExportingCsv(false);
    }
  };

  return (
    <div className={styles.card}>
      {/* Hidden QR used during PDF generation */}
      <div
        style={{ position: "absolute", left: -9999, top: -9999 }}
        ref={qrRef}
      >
        {qrDownloadUrl && <ReactQRCode value={qrDownloadUrl} size={200} />}
      </div>

      <div className={styles.cardHeader}>
        <h3 className={styles.title}>Transactions</h3>
        <Button
          type=""
          value="Refresh"
          icon={<i className="fi fi-rr-refresh"></i>}
          size={"medium"}
          onClick={() => {
            setCurrentPage(1);
            queryClient.invalidateQueries({ queryKey: [QK_ALL_TRANSACTIONS] });
          }}
        >
          Refresh
        </Button>
        <Dropdown menu={{ items: feeTypeItems }} placement="bottomLeft">
          <Button
            type={selectedFeeType ? "primary" : ""}
            icon={<i className="fi fi-rr-filter"></i>}
            size={"medium"}
          >
            {selectedFeeType === "__other__"
              ? "Other"
              : (selectedFeeType ?? "Fee Type")}
          </Button>
        </Dropdown>

        <Dropdown
          menu={{
            items: [
              {
                key: "__all__",
                label: <span>All Statuses</span>,
                onClick: () => {
                  setSelectedPaymentStatus(null);
                  setCurrentPage(1);
                },
              },
              ...PAYMENT_STATUS_OPTIONS.map((opt) => ({
                key: opt.value,
                label: <span>{opt.label}</span>,
                onClick: () => {
                  setSelectedPaymentStatus(opt.value);
                  setCurrentPage(1);
                },
              })),
            ],
          }}
          placement="bottomLeft"
        >
          <Button
            type={selectedPaymentStatus ? "primary" : ""}
            icon={<i className="fi fi-rr-filter"></i>}
            size={"medium"}
          >
            {PAYMENT_STATUS_OPTIONS.find(
              (o) => o.value === selectedPaymentStatus,
            )?.label ?? "Payment Status"}
          </Button>
        </Dropdown>

        <Dropdown
          menu={{
            items: [
              {
                key: "__all__",
                label: <span>All Sessions</span>,
                onClick: () => {
                  setSelectedSession(null);
                  setCurrentPage(1);
                },
              },
              ...sessionsData.map((s) => ({
                key: s.session_name,
                label: <span>{s.session_name}</span>,
                onClick: () => {
                  setSelectedSession(s.session_name);
                  setCurrentPage(1);
                },
              })),
            ],
          }}
          placement="bottomLeft"
        >
          <Button
            type={selectedSession ? "primary" : ""}
            icon={<i className="fi fi-rr-filter"></i>}
            size={"medium"}
          >
            {selectedSession ?? "Session"}
          </Button>
        </Dropdown>

        <DatePicker
          placeholder="Filter By Payment Month"
          className={styles.searchMonthPicker}
          onChange={onPaymentMonthChange}
          picker="month"
          value={selectedPaymentMonth}
        />

        <Input
          placeholder="Search by student email, phone or receipt ID..."
          prefix={<SearchOutlined />}
          className={styles.searchInput}
          allowClear
          onChange={(e) => {
            setSearchQuery(e.target.value);
            setCurrentPage(1);
          }}
          value={searchQuery}
        />
      </div>

      {/* ── Filter Summary Strip ── */}
      {hasActiveFilter && (
        <div className={styles.summaryStrip}>
          {activeFilterChips.length > 0 && (
            <div className={styles.summaryContext}>
              <i
                className="fi fi-rr-chart-pie-alt"
                style={{ marginRight: 5 }}
              />
              Summary for:&nbsp;
              {activeFilterChips.map((chip, i) => (
                <span key={i} className={styles.summaryChip}>
                  {chip}
                </span>
              ))}
            </div>
          )}
          <div className={styles.summaryCards}>
            <div className={styles.summaryCard}>
              <span className={styles.summaryCardLabel}>TOTAL ISSUED</span>
              {summaryLoading ? (
                <Spin size="small" />
              ) : (
                <span className={styles.summaryCardValue}>
                  BDT {Number(summaryData?.total_issued ?? 0).toLocaleString()}
                </span>
              )}
            </div>
            <div
              className={styles.summaryCard}
              style={{
                background: statusCardStyle.bg,
                borderColor: statusCardStyle.border,
              }}
            >
              <span
                className={styles.summaryCardLabel}
                style={{ color: statusCardStyle.text }}
              >
                TOTAL {statusFilterLabel.toUpperCase()}
              </span>
              {summaryLoading ? (
                <Spin size="small" />
              ) : (
                <span
                  className={styles.summaryCardValue}
                  style={{ color: statusCardStyle.text }}
                >
                  BDT{" "}
                  {Number(summaryData?.total_for_status ?? 0).toLocaleString()}
                </span>
              )}
            </div>
          </div>
        </div>
      )}

      <Table
        columns={columns}
        dataSource={rows}
        rowKey="receipt_id"
        loading={isLoading || isFetching}
        size="small"
        className={styles.table}
        scroll={{ x: "max-content" }}
        pagination={{
          current: currentPage,
          pageSize,
          total,
          onChange: (page) => setCurrentPage(page),
          showSizeChanger: false,
          showTotal: () => (
            <div className={styles.paginationBar}>
              <Dropdown
                menu={{ items: rowsMenuItems }}
                trigger={["click"]}
                placement="bottomLeft"
              >
                <button type="button" className={styles.rowsSelector}>
                  <span>Rows: {pageSize}</span>
                  <DownOutlined className={styles.rowsSelectorIcon} />
                </button>
              </Dropdown>
              <span className={styles.paginationShowing}>
                Showing {showingFrom}–{showingTo} of {total.toLocaleString()}
              </span>
              <Button
                icon={<DownloadOutlined />}
                loading={exportingCsv}
                onClick={downloadCSV}
                className={styles.exportCsvBtn}
              >
                Export CSV
              </Button>
            </div>
          ),
        }}
      />

      {/* ── View Details Modal ── */}
      <Modal
        open={!!viewRecord}
        onCancel={() => setViewRecord(null)}
        title="Transaction Details"
        styles={{
          body: {
            maxHeight: "65vh",
            overflowY: "auto",
            paddingRight: 4,
          },
        }}
        footer={[
          <Button
            key="download"
            type="primary"
            loading={downloadingId === viewRecord?.receipt_id}
            onClick={() => handleDownload(viewRecord)}
            icon={<DownloadOutlined />}
          >
            Download Receipt
          </Button>,
          <Button key="close" onClick={() => setViewRecord(null)}>
            Close
          </Button>,
        ]}
        width={700}
        className={styles.transactionDetailsModal}
      >
        {viewRecord && (
          <Descriptions
            column={{ xs: 1, sm: 2, md: 2, lg: 2, xl: 2, xxl: 2, xxxl: 2 }}
            size="small"
            bordered
            style={{ marginTop: 12 }}
          >
            <Descriptions.Item label="Receipt ID">
              {viewRecord.receipt_id ?? "—"}
            </Descriptions.Item>
            <Descriptions.Item label="Date Issued">
              {formatDate(viewRecord.receipt_gen_date)}
            </Descriptions.Item>
            <Descriptions.Item label="Student Name">
              {viewRecord.student_name ?? "—"}
            </Descriptions.Item>
            <Descriptions.Item label="Student Email">
              {viewRecord.student_email ?? "—"}
            </Descriptions.Item>
            <Descriptions.Item label="Student Phone">
              {viewRecord.student_phone ?? "—"}
            </Descriptions.Item>
            <Descriptions.Item label="Session">
              {viewRecord.session ?? "—"}
            </Descriptions.Item>
            <Descriptions.Item label="Fee Type">
              {viewRecord.fee_type_title ?? "—"}
            </Descriptions.Item>
            <Descriptions.Item label="Extra Info">
              {viewRecord.fee_type_xtra_info ?? "—"}
            </Descriptions.Item>
            <Descriptions.Item label="Amount (BDT)">
              {viewRecord.amount != null
                ? `BDT ${Number(viewRecord.amount).toLocaleString()}`
                : "—"}
            </Descriptions.Item>
            <Descriptions.Item label="Payment Mode">
              {viewRecord.payment_mode ?? "—"}
            </Descriptions.Item>
            <Descriptions.Item label="Transaction ID">
              {viewRecord.trxn_id ?? "—"}
            </Descriptions.Item>
            <Descriptions.Item label="Due Date">
              {formatDate(viewRecord.due_date)}
            </Descriptions.Item>
            <Descriptions.Item label="Payment Date">
              {formatDate(viewRecord.payment_date)}
            </Descriptions.Item>
            <Descriptions.Item label="Status">
              <Tag
                color={
                  PAYMENT_STATUS_COLOR[viewRecord.payment_status] ?? "default"
                }
              >
                {paymentStatusLabelMap[viewRecord.payment_status] ??
                  viewRecord.payment_status ??
                  "—"}
              </Tag>
            </Descriptions.Item>
            <Descriptions.Item label="Generated By">
              {viewRecord.receipt_gen_by_email ?? "—"}
            </Descriptions.Item>
            <Descriptions.Item label="Verified By">
              {viewRecord.receipt_verified_by_email ?? "—"}
            </Descriptions.Item>
            <Descriptions.Item label="Student Remarks" span={2}>
              {viewRecord.remarks_by_student ?? "—"}
            </Descriptions.Item>
            <Descriptions.Item label="Payment Proof" span={2}>
              {viewRecord.payment_proof_image_url ? (
                <AntImage
                  src={viewRecord.payment_proof_image_url}
                  width={200}
                  alt="payment proof"
                  style={{ borderRadius: 6, objectFit: "cover" }}
                  preview={{
                    mask: { blur: true },
                    cover: (
                      <Space vertical align="center">
                        <i style={{ fontSize: 30 }} className="fi fi-br-zoom-in"></i>
                      </Space>
                    ),
                  }}
                />
              ) : (
                "—"
              )}
            </Descriptions.Item>
            <Descriptions.Item label="Submitted At">
              {viewRecord.payment_submission_time
                ? getFormattedTime(
                    viewRecord.payment_submission_time,
                    "DD MMM YYYY, h:mm A",
                  )
                : "—"}
            </Descriptions.Item>
          </Descriptions>
        )}
      </Modal>

      {/* ── Change Status Modal ── */}
      <Modal
        open={!!statusRecord}
        onCancel={() => {
          setStatusRecord(null);
          setSelectedStatus(null);
        }}
        title="Change Payment Status"
        footer={[
          <Button
            key="save"
            type="primary"
            loading={statusUpdating}
            disabled={
              !selectedStatus || selectedStatus === statusRecord?.payment_status
            }
            onClick={() =>
              updateStatus({
                receipt_id: statusRecord.receipt_id,
                payment_status: selectedStatus,
                verified_by_email: user?.email ?? null,
                student_email: statusRecord.student_email,
              })
            }
          >
            Save
          </Button>,
          <Button
            key="cancel"
            onClick={() => {
              setStatusRecord(null);
              setSelectedStatus(null);
            }}
          >
            Cancel
          </Button>,
        ]}
      >
        {statusRecord && (
          <div style={{ padding: "8px 0" }}>
            <p style={{ marginBottom: 12, fontSize: "0.85rem", color: "#555" }}>
              Receipt: <strong>{statusRecord.receipt_id}</strong>
            </p>
            <Select
              style={{ width: "100%" }}
              options={PAYMENT_STATUS_OPTIONS}
              value={selectedStatus}
              onChange={setSelectedStatus}
            />
          </div>
        )}
      </Modal>
    </div>
  );
};

export default AllTransactionsComp;
